### PR TITLE
Add Spanish (ES) translation

### PR DESCRIPTION
**Pull request by Roboe**

### CODE REVIEW

**Comment by amotl** [comment]
Thanks a bunch!

**Comment by amotl** [comment]
Dear Roberto,

we just rendered your translations into PDF format for easier reuse:
- https://ptrace.gafam.info/unofficial/pdf/full/lqdn-gafam-poster-es.pdf
- https://ptrace.gafam.info/unofficial/pdf/economy/lqdn-gafam-poster-es.pdf

Enjoy!

**Comment by Roboe** [comment]
Thank you so much! :D

**Comment by amotl** [comment]
Dear @Roboe,

please enjoy the finalized renderings at https://library.gafam.info/#language-es.

Thanks again!

**Comment by Roboe** [comment]
They look stunning! Thank you for notifying, @amotl

**Pull request merged**
