### PR TITLE
Added a Swedish translation

### PR DESCRIPTION
**Pull request by PierreMesure**

### CODE REVIEW

**Comment by amotl** [comment]
Thanks a bunch!

**Comment by amotl** [comment]
P.S.: After rendering, you can see the footer text of the translation of the Apple poster (the second one) is lacking newlines. We will also update this when adjusting the layout for optimal rendering. We humbly ask for your patience.

**Comment by PierreMesure** [comment]
No hurry!

**Comment by amotl** [comment]
Dear @PierreMesure,

please enjoy the finalized renderings at https://library.gafam.info/#language-sv.

Thanks again!

**Pull request merged**
