### PR TITLE
Esperanta traduko (bezonas relegante) kaj korekto

### PR DESCRIPTION
**Pull request by DavidLibeau**
Traduction en Espéranto (relecture nécessaire) et correction
Esperanto translation (proofreading required) and correction

### CODE REVIEW

**Comment by amotl** [comment]
Thank you very much, David!

You can see a rough preview of your work at:
- https://examples.posterkit.net/lqdn-gafam-campaign/poster.html?lang=eo&name=google&passepartout=true
- https://examples.posterkit.net/lqdn-gafam-campaign/poster.html?lang=eo&name=apple&passepartout=true
- etc. ...

Please be aware that this is automatically layouted using HTML/CSS/JS and not with Adobe Illustrator as the original PDF files from LQDN are. Also, this is still in a very early state and barely able to walk.

However, we believe it is enjoyable already. For proper printing, just strip away the `passepartout=true` query parameter.

**Comment by DavidLibeau** [comment]
Cool !
Can you in some way delete the "é" of "Espéranto" (that's the french work for "Esperanto"). Thanks

**Comment by amotl** [comment]
Dear David, we just corrected some occurrences while working on the source base. Let us know if you spot any leftovers. Thanks!

**Comment by amotl** [comment]
Dear David,

you can now also have a look at the preview of your work in PDF format at [lqdn-gafam-poster-eo.pdf](https://ptrace.gafam.info/unofficial/pdf/lqdn-gafam-poster-eo.pdf). We still have to adjust the font, though.

This was produced by a quick hack in form of [makepdf.py](https://github.com/posterkit/posterkit-o-mat/blob/master/htdocs/examples/lqdn-gafam-campaign/makepdf.py) on behalf of the [PosterKit software](https://github.com/posterkit/posterkit-o-mat).

Enjoy!

**Comment by amotl** [comment]
Dear @DavidLibeau,

please enjoy the finalized renderings at https://library.gafam.info/#language-eo.

Thanks again!

**Pull request merged**
